apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: upload-terraform-and-run-docker
  description: Template to upload Terraform files for frontend and backend, then deploy Docker images to Kubernetes.
spec:
  owner: your-team
  type: service
  templater: handlebars
  path: './templates/upload-terraform-and-run-docker'
  steps:
    - name: Upload Frontend Terraform
      action: backstage:upload-files
      input:
        files:
          - path: './frontend/terraform/main.tf'
            destination: 'terraform/frontend/'
    - name: Upload Backend Terraform
      action: backstage:upload-files
      input:
        files:
          - path: './backend/terraform/main.tf'
            destination: 'terraform/backend/'
    - name: Run Terraform for Frontend
      action: backstage:run-terraform
      input:
        directory: 'terraform/frontend/'
        command: 'apply'
    - name: Run Terraform for Backend
      action: backstage:run-terraform
      input:
        directory: 'terraform/backend/'
        command: 'apply'
    - name: Deploy Docker Image for Frontend
      action: backstage:deploy-docker
      input:
        image: 'frontend-image'
        kubernetes_cluster: 'your-cluster-name'
    - name: Deploy Docker Image for Backend
      action: backstage:deploy-docker
      input:
        image: 'backend-image'
        kubernetes_cluster: 'your-cluster-name'
