apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component
  description: "A description of my component"
  tags:
    - web
    - api
spec:
  type: service
  lifecycle: production 
  owner: team-a
  dependsOn:
    - api: my-existing-api
