apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-app
  description: "A description of my component"
  tags:
    - web
    - api
spec:
  profile:
    displayName: my-backstage-app
  targets:
    - '../template/upload-terraform-and-run-docker.yaml'
  type: service
  lifecycle: production 
  owner: team-a
  dependsOn:
    - "component:default/my-existing-api"
